name: Publishing development stage

on:
  push:
    branches:
      - feat/gatsby

jobs:
  run:
    runs-on: ubuntu-latest
    environment: development
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm ci

      - name: Add .env.development
        run: |
          echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> .env.development
          echo "AWS_BUCKET_PREFIX=${{ secrets.AWS_BUCKET_PREFIX }}" >> .env.development
          echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env.development
          echo "GATSBY_API_BASE=${{ secrets.GATSBY_API_BASE }}" >> .env.development

      - name: Build
        run: npm run build:dev

      - name: Deploy
        run: npm run deploy:dev:ci
